### ISSUE TITLE
Socket join connection feedback

### ISSUE THREAD

**Issue by YingLiang2** [jonathanplacatka/typing-game#10]
Socket connection is not instantaneous, so need to deal with it to let client know they are connected. 

So currently when we click the "Connect" button, there is no feedback to let the user know they are connected.

**Comment by jonathanplacatka** [comment]
we're using issues now? so professional

short term we could add a message telling the user they're connected? Eventually we'll want to only load the game component once they're connected. and some sort of spinner/loading icon

**Comment by YingLiang2** [comment]
Yeah we can do a message for now, it's just that there is a delay for a connection, so need to figure out a way to check if connected. 

Of course we can check after a delay, but idk.

**Comment by jonathanplacatka** [comment]
socket.on('connect') should work for this no? see my original socket component code

**Comment by YingLiang2** [comment]
Yeah I think that should work.

**Comment by jonathanplacatka** [comment]
Added this in #12 by showing/hiding the game window based on socket connection

**Comment by jonathanplacatka** [comment]
Added this in #12 by showing/hiding the game window based on socket connection

**Comment by jonathanplacatka** [comment]
Added this in #12 by showing/hiding the game window based on socket connection
