### ISSUE TITLE
Caret should stay in fixed position after typing in last character.

### ISSUE THREAD

**Issue by YingLiang2** [jonathanplacatka/typing-game#30]
Currently when the user types in the last character and its wrong, the caret will move to the right side of the last character but this motion is not fixed for the situation when we backspace, then type in multiple incorrect characters, the caret will then move slightly more to the right of the last character. This isn't a huge issue, but it maybe it should be addressed in the future as it may affect our css styling.

Steps to reproduce:

1. Enter an incorrect last character
2. Backspace that last character
3. Enter in multiple incorrect chars to see the caret have moved slightly further to the right.

**Comment by jonathanplacatka** [comment]
fixed in #55
