### ISSUE TITLE
Caret errors / mispositions position in the game

### ISSUE THREAD

**Issue by YingLiang2** [jonathanplacatka/typing-game#38]
Anytime we seem to re-render the gametext / input and typing, it seems to break and we will begin typing errors.

Examples:

* A user leaving during the game
* When we zoom the screen in and out (CTRL + / -)

We also break the game / caret position when we have command deletes / backspaces such as:

* CTRL + Backspace
* CTRL + A -> Backspace

After these commands are inputted it will not recognize any correct characters being typed in.

**Comment by jonathanplacatka** [comment]
fixed in #55
